baseURL = 'https://ydzhou.github.io'
languageCode = 'en-us'
hasCJKLanguage = true
googleAnalytics = 'G-NGR0WHS7KP'
defaultContentLanguage = 'zh'

[params]
mainSections = ['notes']
paginationSize = 5

[languages]
[languages.zh]
languageName = 'ğŸ‡¨ğŸ‡³'
title = 'ä¸€æ— æ‰€æœ‰åœ°æµæµª'
weight = 1

[languages.en]
languageName = 'ğŸ‡ºğŸ‡¸'
title = 'Nothing Owned'
weight = 2

# [[languages.zh.menu.main]]
# name = "æŠ€æœ¯"
# url = "/tech"
# weight = 2

# [[languages.zh.menu.main]]
# name = "é—²æ‰¯"
# url = "/random"
# weight = 3

# [[languages.zh.menu.main]]
# name = "å…³äº"
# url = "/about"
# weight = 4

# [[languages.en.menu.main]]
# name = "Tech"
# url = "/tech"
# weight = 2

# [[languages.en.menu.main]]
# name = "Random"
# url = "/random"
# weight = 3

# [[languages.en.menu.main]]
# name = "About"
# url = "/about"
# weight = 4
