baseURL = 'https://ydzhou.github.io'
languageCode = 'en-us'
title = 'æµ·è¾¹çš„è‰¾å°”ç»´æ–¯'
hasCJKLanguage = true
googleAnalytics = 'G-NGR0WHS7KP'
defaultContentLanguage = 'zh'

[params]
mainSections = ['tech', 'random']
paginationSize = 5

[languages]
[languages.zh]
languageName = 'ðŸ‡¨ðŸ‡³ä¸­æ–‡'
title = 'æµ·è¾¹çš„è‰¾å°”ç»´æ–¯'
weight = 1

[languages.en]
languageName = 'ðŸ‡ºðŸ‡¸English'
title = 'yzbythesea'
weight = 2

[[languages.zh.menu.main]]
name = "ä¸»é¡µ"
url = "/"
weight = 1

[[languages.zh.menu.main]]
name = "æŠ€æœ¯"
url = "/tech"
weight = 2

[[languages.zh.menu.main]]
name = "é—²æ‰¯"
url = "/random"
weight = 3

[[languages.zh.menu.main]]
name = "å…³äºŽ"
url = "/about"
weight = 4

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Tech"
url = "/tech"
weight = 2

[[languages.en.menu.main]]
name = "Random"
url = "/random"
weight = 3

[[languages.en.menu.main]]
name = "About"
url = "/about"
weight = 4
