baseURL = 'https://ydzhou.github.io'
languageCode = 'en-us'
hasCJKLanguage = true
googleAnalytics = 'G-NGR0WHS7KP'
defaultContentLanguage = 'en'

[params]
mainSections = ['tech']
paginationSize = 5

[languages]
[languages.zh]
languageName = 'ğŸ‡¨ğŸ‡³'
title = 'ä¸€æ— æ‰€æœ‰åœ°æµæµª'
weight = 1

[languages.en]
languageName = 'ğŸ‡ºğŸ‡¸'
title = 'Nothing Owned'
weight = 2
